### ISSUE TITLE
Name This Application

### ISSUE THREAD

**Issue by craig-riecke** [rubyforgood/share_christmas#1]
_Share Your Christmas_ is the name for the campaign, but the application should work in all campaigns that match recipients with donors providing a good/service.  Initially I'm calling it _Share Your Holiday_ and "Holiday" could mean Christmas (donations = presents) or Thanksgiving (donations = turkeys or meals).  But it should also work for Back To School (donations = backpacks full of school supplies) ... but no child on Earth would call that a Holiday!

**Comment by nolds9** [comment]
Throwing out some ideas for an app name:
- ShareJoy
- GiveAGift
- ProjectShare

**Comment by craig-riecke** [comment]
We're gonna call it Share Your Happiness or Share Your Joy, but Durham Volunteer Center may wish to call it something else.  In fact, a particular volunteer center may want to choose their own Name and Logo for the concept, which is something we can add to the Volunteer Center model later.  

This is good for our purposes!
