### ISSUE TITLE
Add testing tools

### ISSUE THREAD

**Issue by jaydorsey** [rubyforgood/share_christmas#100]
I'm partial to RSpec, FactoryGirl, Poltergeist, and the Shoulda Matchers with the headless gem running. Any objections or preferences for others? I can set this up and start writing feature tests

**Comment by craig-riecke** [comment]
I'm familiar with all of these except Shoulda, so if you could write the first tests, that'd be great.

So Rspec-rails is in the Gemfile already.  There are no tests as yet, but running `bundle exec rspec` I get:

```
NoMethodError: undefined method `setup' for ActiveAdmin:Module
  /Users/cr396/src/share_christmas/config/initializers/active_admin.rb:3:in `<top (required)>'
  /Users/cr396/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
  /Users/cr396/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
  /Users/cr396/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
  /Users/cr396/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
  /Users/cr396/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:652:in `block in load_config_initializer'
  /Users/cr396/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument
   etc.
```

I tried adding `require 'activeadmin'` to `config/initializers/active_admin.rb` as the Internet suggested, but that doesn't seem to work.

**Comment by jaydorsey** [comment]
I'll tackle this tonight and make sure RSpec/FactoryGirl/etc. is working

**Comment by jaydorsey** [comment]
That issue with ActiveAdmin was resolved by moving the file that was in /lib into the initializers block. I didn't spend a lot of time debugging, but I'm assuming it's related to load path & boot order. I didn't get into it because my vote is still to drop ActiveAdmin and do custom/bespoke interfaces

If we had to grant someone access to the database that didn't have access to the codebase/server (for debugging), ActiveAdmin would make sense. Or if we had someone devoted to becoming an ActiveAdmin expert, ActiveAdmin would make sense. I'd suggest an approach where we start with a very minimal feature set (an admin dashboard for volunteer centers, and one for organizations) and add on.

ActiveAdmin gives us the kitchen sink and now we need to figure out what to remove (if we're planning to keep it)

It was great for the demo though

**Comment by craig-riecke** [comment]
Yeah, I'm beginning to agree for the reasons you cited, plus:
- Despite lots of usage, ActiveAdmin seems rough.  This Rspec issue is just the tip of the iceberg if you read their issues database, it's huge.
- Volunteer Center Admin, when it's all done, will actually be smaller than Org Admin (which doesn't use ActiveAdmin)
- The data model is complex, and shielding that complexity from users is going to outstrip ActiveAdmin's capabilities.  I see it already in OrgAdmin.
