### ISSUE TITLE
Add TravisCI 

### ISSUE THREAD

**Issue by craig-riecke** [rubyforgood/share_christmas#109]
- Have TravisCI run the tests automatically on a pull request, or merging into Master
- Add a TravisCI badge to README.md
- Only allow merges to master when tests pass (if this becomes a PITA, we can turn it off).

**Comment by atzorvas** [comment]
@craig-riecke I would suggest using the Task List notation and add the related issues

**Comment by craig-riecke** [comment]
@atzorvas Good idea!  Will try to remember that for future tasks...
