### ISSUE TITLE
Remove VolunteerCenter model & table

### ISSUE THREAD

**Issue by atzorvas** [rubyforgood/share_christmas#128]
Following [Hack NIght Discussion issue](https://github.com/rubyforgood/share_christmas/issues/119)  the MPV will be developed only for the [Durham, NC Volunteer Center](http://www.thevolunteercenter.org/), so we can simplify our codebase as we won't have to deal with handling multiple volunteer centers.

**Comment by craig-riecke** [comment]
I don't see anything left to do on this, so closing...
