### ISSUE TITLE
Image upload for campaign

### ISSUE THREAD

**Issue by jaydorsey** [rubyforgood/share_christmas#25]
Add the ability to upload a logo/image for the campaign

The volunteer center would upload this when they create the campaign. Possibly use paperclip gem

**Comment by AEgan** [comment]
I 👍 to paperclip for this. Heroku + S3 + Paperclip = [solved problem](https://devcenter.heroku.com/articles/paperclip-s3)

**Comment by AEgan** [comment]
I created a work in progress branch based on the heroku changes I made.

[Here](https://github.com/rubyforgood/share_christmas/compare/aegan/heroku...aegan/paperclip?expand=1) is a comparison of those changes with the heroku branch. We still may want to decide on different sizes to use for the images, and what to do about AWS credentials. But this is a starting point that will upload to S3 in production.
