### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by AEgan** [rubyforgood/share_christmas#28]
We need to deploy the app to production, which would involve a few steps.

We've been talking about deploying to Heroku, and [there's a guide](https://devcenter.heroku.com/articles/getting-started-with-rails4) if we decide to go that route.
We would also need to move sensitive information, like passwords for mailer configuration and the admin created in seeds, to environment variables and make sure those are set on Heroku.

If we implement #25 and #26 we need to configure uploads to be saved on S3.

We'd also want to make sure we all have deployment abilities without sharing login info. I'm not sure if [Heroku Organizations](https://devcenter.heroku.com/categories/organization-accounts) is the way to go, but Heroku does have something for this.

**Comment by AEgan** [comment]
I'll look into this. I can create the heroku app and add collaborators, then transfer ownership later to someone else.

I'll worry about the image uploads when we get there.

**Comment by craig-riecke** [comment]
Sean said Heroku will give non-profits a Hobby account for free.  I don't know what the terms are.  It's quite possible we can get a better deal elsewhere, but this can be researched post RFG 2016.  (I'm willing to do the legwork on it).

**Comment by AEgan** [comment]
I'm going to close this as it can be deployed to Heroku, and add a new stretch issue to deal with what happens after this weekend

**Comment by AEgan** [comment]
#50
