### ISSUE TITLE
Create campaign

### ISSUE THREAD

**Issue by jaydorsey** [rubyforgood/share_christmas#36]
As an Organization admin, I should be able to create a campaign. This campaign should include some basic information and allow for the upload of an image

Related to #25

**Comment by jaydorsey** [comment]
routes:
- /:campaign_slug => page user sees for campaign

**Comment by craig-riecke** [comment]
Related to #54.

**Comment by craig-riecke** [comment]
Volunteer Centers will actually create the campaign, but organizations will join them.  So this needs to be done for Alpha.
